### ISSUE TITLE
[FEATURE]: Light/Dark/Custom Theming

### ISSUE THREAD

**Issue by ghost** [gsporto/youtube-chat-thing#1]
Heya!

I found this repository and thought it was super useful.

I did want to know if there'd be any plans for custom theming or dark/light mode? Basically, I want to be able to change my background to a light mint colour and slightly grey text colour.

Thanks,
- Alex

**Comment by gsporto** [comment]
Hey, I'm glad you found it useful!

This project is essentially a wrapper around YouTube's live chat popout, which means we can't directly modify YouTube's themes or chat behavior. However, I did manage to add a feature that lets you toggle between YouTube's default dark and light modes. You can check out the implementation in this 19c66d5f42846cf7303ec2e93306fc7c5d4c328a.

Thanks 🫡
