### ISSUE TITLE
Update title when chat loaded

### ISSUE THREAD

**Issue by stevencrader** [gsporto/youtube-chat-thing#2]
Once a chat is loaded, could the page title be updated with the YT user's name or at least the handle?

When having multiple chats open, it is hard to figure out the right one to use since they all say "Youtube Chat Thing".

If you are interested in this, I can submit a PR.

**Comment by gsporto** [comment]
Hi, thanks for the suggestion!
I’ve added the handle to the title in commit 94f5de6. Always open to more suggestions and pull requests!
